<Project>

    <PropertyGroup>
        <PackageId>CSharpHelperExtensions</PackageId>
        <Version>2.0.0</Version>
        <PackageVersion>2.0.0</PackageVersion>
        <Authors>Bipin Radhakrishnan</Authors>
        <Description>A set of helper extension methods that are used very often when coding</Description>
        <PackageTags>extensions;helpers;enumerable;string;utilities;csharp</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/rbipin/dry-extensions-csharp</PackageProjectUrl>
        <RepositoryUrl>https://github.com/rbipin/dry-extensions-csharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>logo-nuget.png</PackageIcon>
        <PackageReleaseNotes></PackageReleaseNotes>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)assets\logo-nuget.png" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
