<Project>
    <PropertyGroup>
        <PackageId Condition="'$(MSBuildProjectName)' == 'CSharpHelperExtensions'"
        >
            CSharpHelperExtensions</PackageId>
        <Version>2.0.0</Version>
        <Authors>Bipin Radhakrishnan</Authors>
        <Description>A set of helper extension methods that are used very often when coding</Description>
        <PackageTags>extensions;helpers;enumerable;string;utilities;csharp</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/rbipin/dry-extensions-csharp</PackageProjectUrl>
        <RepositoryUrl>https://github.com/rbipin/dry-extensions-csharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>docs/README.md</PackageReadmeFile>
        <PackageIcon>logo-nuget.png</PackageIcon>
        <PackageReleaseNotes></PackageReleaseNotes>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)docs\README.md" Pack="true" PackagePath="docs\" />
        <None Include="$(MSBuildThisFileDirectory)assets\logo-nuget.png" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
