name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore src/CSharpHelperExtensions.slnx
    - name: Build
      run: dotnet build src/CSharpHelperExtensions.slnx --no-restore
    - name: Test
      run: dotnet test src/CSharpHelperExtensions.slnx --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ./

    - uses: dorny/test-reporter@v3
      if: always()
      with:
        path: test-results.trx
        name: dotnet tests
        reporter: 'dotnet-trx'
